In [1]:
try:
    import jupytercloud.nirvana as jn
except:
    class jn:
        @staticmethod
        def get_named_input(name, local_path):
            return local_path
        
        @staticmethod
        def get_custom_output(index, local_path):
            from pathlib import Path
            return Path(local_path)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

NUM_SAMPLES = 20
# NUM_MODELS = 5 # deprecated, recommended at least 5 models tho
BOOTSTRAP_RATIO = 0.7

In [2]:
from statsmodels.stats.weightstats import zconfint, ztest
import yt.wrapper as yt

client = yt.YtClient('hahn')

def yt_read(path, client=client):
    result = yt.read_table(path, format='yson', client=client)
    df = pd.DataFrame(list(result))
    if df.empty:
        schema = yt.get_attribute(path, 'schema', client=client)
        return pd.DataFrame(columns=tuple(column['name'] for column in schema))
    else:
        return df
    
def local_read(path):
    return pd.read_csv(jn.get_named_input(path, local_path=path), sep='\t')

In [3]:
random_df = local_read('random.tsv')
policy_dfs = []
CUR_NUM_MODEL = 0
while True:
    try:
        policy_dfs.append(local_read(f'policy_{CUR_NUM_MODEL}.tsv'))
    except:
        print(f"Number of models {CUR_NUM_MODEL}")
        break
    CUR_NUM_MODEL+=1

Number of models 5

In [4]:
metric_names = list(random_df.columns)
for n in ["rid", "show", "priority_show", "candidate_num"]:
    metric_names.remove(n)
metric_names

['click', 'nsr']

In [5]:
def compute_policy_stats(random_df, policy_df):
    # Бёрём пересечение поклазов по политике и показов по рандому
    policy = random_df.merge(policy_df, on=['rid', 'show'], how='inner').drop('rid', axis=1).drop('priority_show', axis=1)

    # Нормируем метрики на количество кандидтов (чтобы экстраполировать пересечение с рандомом на полный размер рандома)
    for metric_name in metric_names:
        policy[metric_name] *= policy.candidate_num

    # Группируем по тритменту, считаем экстраполированные показы
    policy = policy.groupby('show').sum().rename({'candidate_num':'shows'}, axis=1)

    # Добавляем сумму
    policy.loc['overall'] = policy.sum(axis=0)
    
    # Считаем метрики удельно на экстраполированный показ
    for metric in metric_names:
        policy[f'{metric}_by_show'] = policy[metric] / policy.shows
    
    return policy

def compute_random_stats(random_df):
    # Удаляем candidate_num, добавляем shows=1 (тут использована замена, чтобы сохранить порядок колонок)
    policy = random_df.rename({'candidate_num':'shows'}, axis=1).drop('rid', axis=1).drop('priority_show', axis=1)
    policy.shows = 1
    
    # Группируем по тритменту
    policy = policy.groupby('show').sum()

    # Добавляем сумму
    policy.loc['overall'] = policy.sum(axis=0)

    # Считаем метрики удельно на показ
    for metric in metric_names:
        policy[f'{metric}_by_show'] = policy[metric] / policy.shows
    
    return policy

In [6]:
# Считаем усредненные метрики по декартову произведению моделей и выборок
policy_stats_overall = None
policy_stats_overall_with_mean_std = None
for policy_df in policy_dfs:
    for num_sample in range(NUM_SAMPLES):
        _, random_df_sample = train_test_split(random_df, test_size=BOOTSTRAP_RATIO)
        policy_stats = compute_policy_stats(random_df_sample, policy_df)
        
        if policy_stats_overall is None:
            policy_stats_overall =  pd.DataFrame(index = policy_stats.index, columns = policy_stats.columns)
            policy_stats_overall_with_mean_std =  pd.DataFrame(index = policy_stats.index, columns = policy_stats.columns)
            for col in policy_stats_overall.columns:
                policy_stats_overall[col] = policy_stats_overall[col].apply(lambda d: d if isinstance(d, list) else [])
        else:
            for index in policy_stats.index:
                if index not in policy_stats_overall.index:
                    policy_stats_overall.loc[index] = [[] for _ in range(len(policy_stats_overall.columns))]
                    policy_stats_overall_with_mean_std.loc[index] = [np.nan for _ in range(len(policy_stats_overall.columns))]
                 
        for row in policy_stats.iterrows():
            index = row[0]
            for col, value in row[1].items():
                policy_stats_overall.loc[index, col].append(policy_stats.loc[index, col])

for row in policy_stats_overall.iterrows():
    index = row[0]
    for col, value in row[1].items():
        policy_stats_overall_with_mean_std.loc[index, col] = (np.array(policy_stats_overall.loc[index, col]).mean(),
                                                np.array(policy_stats_overall.loc[index, col]).std())

policy_stats_overall_with_mean_std

,shows,click,nsr,click_by_show,nsr_by_show
show,,,,,
2195,"(3.3838383838383836, 1.1255263254290198)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
2266,"(606058.88, 777.0708755319556)","(3363.84, 53.15744914873174)","(3363.84, 53.15744914873174)","(0.005550359728857147, 8.792316616343728e-05)","(0.005550359728857147, 8.792316616343728e-05)"
2709,"(48807.56, 191.0703702827835)","(45.4, 5.635601121442149)","(45.4, 5.635601121442149)","(0.0009302088044678824, 0.00011558624726552869)","(0.0009302088044678824, 0.00011558624726552869)"
3548,"(461804.73, 560.9292086351004)","(953.68, 28.057754721288727)","(953.68, 28.057754721288727)","(0.0020651141229192376, 6.067151041656402e-05)","(0.0020651141229192376, 6.067151041656402e-05)"
5617,"(4.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
5866,"(296092.3, 593.0106997348362)","(290.55, 22.94836595489971)","(290.55, 22.94836595489971)","(0.0009812779093443203, 7.748471497620618e-05)","(0.0009812779093443203, 7.748471497620618e-05)"
5933,"(2.2637362637362637, 0.8097641066787051)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
6001,"(17.96, 5.580179208591781)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
6106,"(596947.64, 718.7733651158757)","(3157.31, 61.28795885000577)","(3157.31, 61.28795885000577)","(0.005289091101788256, 0.00010251545326923848)","(0.005289091101788256, 0.00010251545326923848)"
6217,"(2540.37, 43.73137432096092)","(2.05, 0.8046738469715541)","(2.05, 0.8046738469715541)","(0.0008069529079320302, 0.0003163427308573917)","(0.0008069529079320302, 0.0003163427308573917)"
6219,"(118011.11, 311.1882033432501)","(62.59, 6.123879489343336)","(62.59, 6.123879489343336)","(0.0005303770759156496, 5.192773367243997e-05)","(0.0005303770759156496, 5.192773367243997e-05)"
6222,"(246465.82, 587.4844573263194)","(682.76, 35.41217869603619)","(682.76, 35.41217869603619)","(0.0027701882053248663, 0.00014332745287004797)","(0.0027701882053248663, 0.00014332745287004797)"
6352,"(221420.08, 535.0271148269029)","(228.83, 16.30340761926782)","(228.83, 16.30340761926782)","(0.0010334685094701799, 7.364891088750657e-05)","(0.0010334685094701799, 7.364891088750657e-05)"
6389,"(354513.62, 563.5123917004842)","(319.99, 20.80408373372882)","(319.99, 20.80408373372882)","(0.0009026301365561118, 5.884853851490659e-05)","(0.0009026301365561118, 5.884853851490659e-05)"
6603,"(261080.02, 482.8408222178403)","(58.19, 9.373041128683901)","(58.19, 9.373041128683901)","(0.00022288010519395138, 3.5900619354056694e-05)","(0.00022288010519395138, 3.5900619354056694e-05)"
6658,"(6.33, 1.833330303027799)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
overall,"(3213774.35, 998.9048240448137)","(9165.19, 102.90721014583964)","(9165.19, 102.90721014583964)","(0.0028518461167991813, 3.2005218503389e-05)","(0.0028518461167991813, 3.2005218503389e-05)"

In [7]:
random_stats = compute_random_stats(random_df)
random_stats

             shows   click     nsr  click_by_show  nsr_by_show
show
2195           4.0     0.0     0.0       0.000000     0.000000
2266      302619.0  1711.0  1711.0       0.005654     0.005654
2709       35049.0    31.0    31.0       0.000884     0.000884
3548      292846.0   653.0   653.0       0.002230     0.002230
5617           1.0     0.0     0.0       0.000000     0.000000
5866      102556.0    74.0    74.0       0.000722     0.000722
5933           2.0     0.0     0.0       0.000000     0.000000
6001           5.0     0.0     0.0       0.000000     0.000000
6106      306356.0  1715.0  1715.0       0.005598     0.005598
6217        2003.0     3.0     3.0       0.001498     0.001498
6219       91919.0    44.0    44.0       0.000479     0.000479
6222       98473.0   242.0   242.0       0.002458     0.002458
6352      113476.0    89.0    89.0       0.000784     0.000784
6389      184872.0   148.0   148.0       0.000801     0.000801
6603      160803.0    27.0    27.0       0.000168     0.000168
6658           6.0     0.0     0.0       0.000000     0.000000
overall  1690990.0  4737.0  4737.0       0.002801     0.002801

In [8]:
priority_stats = compute_policy_stats(random_df, random_df[random_df.show == random_df.priority_show][['rid','show']])
priority_stats

             shows    click      nsr  click_by_show  nsr_by_show
show
2195           3.0      0.0      0.0       0.000000     0.000000
2266      850828.0   4718.0   4718.0       0.005545     0.005545
2709       17870.0     14.0     14.0       0.000783     0.000783
3548      558237.0   1075.0   1075.0       0.001926     0.001926
5617           4.0      0.0      0.0       0.000000     0.000000
5866       17011.0      0.0      0.0       0.000000     0.000000
5933           1.0      0.0      0.0       0.000000     0.000000
6106      838814.0   4431.0   4431.0       0.005282     0.005282
6217        1040.0      3.0      3.0       0.002885     0.002885
6219       48192.0     20.0     20.0       0.000415     0.000415
6222      290056.0    817.0    817.0       0.002817     0.002817
6352       39594.0     20.0     20.0       0.000505     0.000505
6389       54832.0     27.0     27.0       0.000492     0.000492
6603       86757.0     15.0     15.0       0.000173     0.000173
6658           3.0      0.0      0.0       0.000000     0.000000
overall  2803242.0  11140.0  11140.0       0.003974     0.003974

In [9]:
print('Uplift from random')
for metric in metric_names:
    uplift = policy_stats_overall_with_mean_std[f'{metric}_by_show']['overall'][0] / random_stats[f'{metric}_by_show']['overall']
    print(f'{metric}:\t{uplift}')
print()

print('Uplift from priority')
for metric in metric_names:
    uplift = policy_stats_overall_with_mean_std[f'{metric}_by_show']['overall'][0] / priority_stats[f'{metric}_by_show']['overall']
    print(f'{metric}:\t{uplift}')
print()

print('shows by random:              ' + str(random_stats['shows']['overall']))
print('extrapolated shows by policy: ' + str(policy_stats_overall_with_mean_std['shows']['overall'][0] / BOOTSTRAP_RATIO))

Uplift from random
click:	1.0180374213734953
nsr:	1.0180374213734953

Uplift from priority
click:	0.7176314912161912
nsr:	0.7176314912161912

shows by random:              1690990.0
extrapolated shows by policy: 4591106.214285715